taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

theme = "radion"
# The URL the site will be built for
base_url = "https://hiddevogelpoel.github.io"
title = "hidde's ramblings"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"

[search]
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
radion_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
radion_title = "hidde's rambling dump"

# Nicer codeblocks with copy to clipboard
codeblock = true

# Enable MathJax support
latex = true

# Enable search bar
enable_search = false

# Light/Dark Mode set
theme = "toggle" # options: {light, dark, auto, toggle}

# Whether to display favicon
favicon = true

comments = false
author = "Hidde"
github = "https://github.com/hiddevogelpoel"